# Generated by Django 5.1.7 on 2025-03-15 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vardiya Adı')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Vardiya',
                'verbose_name_plural': 'Vardiyalar',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Departman Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Yıllık İzin'), ('sick', 'Hastalık İzni'), ('maternity', 'Doğum İzni'), ('paternity', 'Babalık İzni'), ('marriage', 'Evlilik İzni'), ('bereavement', 'Ölüm İzni'), ('unpaid', 'Ücretsiz İzin'), ('other', 'Diğer')], max_length=20, verbose_name='İzin Tipi')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('reason', models.TextField(verbose_name='Sebep')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İzin',
                'verbose_name_plural': 'İzinler',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Dönem Başlangıcı')),
                ('period_end', models.DateField(verbose_name='Dönem Sonu')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Temel Maaş')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Fazla Mesai Saati')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Fazla Mesai Ücreti (Saatlik)')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fazla Mesai Tutarı')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prim')),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ödenekler')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kesintiler')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vergi')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Maaş')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ödeme Yöntemi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('approved', 'Onaylandı'), ('paid', 'Ödendi'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payrolls', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maaş Bordrosu',
                'verbose_name_plural': 'Maaş Bordroları',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(verbose_name='Değerlendirme Tarihi')),
                ('period_start', models.DateField(verbose_name='Dönem Başlangıcı')),
                ('period_end', models.DateField(verbose_name='Dönem Sonu')),
                ('punctuality_rating', models.PositiveSmallIntegerField(choices=[(1, 'Çok Kötü'), (2, 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Çok İyi')], verbose_name='Dakiklik Puanı')),
                ('attendance_rating', models.PositiveSmallIntegerField(choices=[(1, 'Çok Kötü'), (2, 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Çok İyi')], verbose_name='Devam Puanı')),
                ('productivity_rating', models.PositiveSmallIntegerField(choices=[(1, 'Çok Kötü'), (2, 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Çok İyi')], verbose_name='Verimlilik Puanı')),
                ('quality_rating', models.PositiveSmallIntegerField(choices=[(1, 'Çok Kötü'), (2, 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Çok İyi')], verbose_name='Kalite Puanı')),
                ('teamwork_rating', models.PositiveSmallIntegerField(choices=[(1, 'Çok Kötü'), (2, 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Çok İyi')], verbose_name='Takım Çalışması Puanı')),
                ('communication_rating', models.PositiveSmallIntegerField(choices=[(1, 'Çok Kötü'), (2, 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Çok İyi')], verbose_name='İletişim Puanı')),
                ('overall_rating', models.PositiveSmallIntegerField(choices=[(1, 'Çok Kötü'), (2, 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Çok İyi')], verbose_name='Genel Puan')),
                ('strengths', models.TextField(blank=True, null=True, verbose_name='Güçlü Yönler')),
                ('areas_for_improvement', models.TextField(blank=True, null=True, verbose_name='Geliştirilmesi Gereken Alanlar')),
                ('goals', models.TextField(blank=True, null=True, verbose_name='Hedefler')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Yorumlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_performances', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performans Değerlendirmesi',
                'verbose_name_plural': 'Performans Değerlendirmeleri',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Pozisyon')),
                ('employment_type', models.CharField(choices=[('full_time', 'Tam Zamanlı'), ('part_time', 'Yarı Zamanlı'), ('contract', 'Sözleşmeli'), ('intern', 'Stajyer'), ('temporary', 'Geçici')], default='full_time', max_length=20, verbose_name='Çalışma Tipi')),
                ('hire_date', models.DateField(verbose_name='İşe Başlama Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='İşten Ayrılma Tarihi')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maaş')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Acil Durum Kişisi')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Acil Durum Telefonu')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Banka Hesabı')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vergi Numarası')),
                ('social_security_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='SGK Numarası')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staff.department')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personel Profili',
                'verbose_name_plural': 'Personel Profilleri',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Giriş Saati')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Çıkış Saati')),
                ('status', models.CharField(choices=[('present', 'Mevcut'), ('absent', 'Yok'), ('late', 'Geç'), ('half_day', 'Yarım Gün'), ('leave', 'İzinli')], default='present', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devam Kaydı',
                'verbose_name_plural': 'Devam Kayıtları',
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.shift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vardiya Ataması',
                'verbose_name_plural': 'Vardiya Atamaları',
                'ordering': ['date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
