# Generated by Django 5.1.7 on 2025-03-15 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Ekipman Kategorisi',
                'verbose_name_plural': 'Ekipman Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='ReservableArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Alan Adı')),
                ('area_type', models.CharField(choices=[('court', 'Kort'), ('pool', 'Havuz'), ('sauna', 'Sauna'), ('massage', 'Masaj Odası'), ('meeting', 'Toplantı Odası'), ('other', 'Diğer')], max_length=20, verbose_name='Alan Tipi')),
                ('location', models.CharField(max_length=100, verbose_name='Konum')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasite')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saatlik Ücret')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reservable_areas/', verbose_name='Görsel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Rezerve Edilebilir Alan',
                'verbose_name_plural': 'Rezerve Edilebilir Alanlar',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ekipman Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('quantity', models.PositiveIntegerField(verbose_name='Toplam Adet')),
                ('available_quantity', models.PositiveIntegerField(verbose_name='Müsait Adet')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saatlik Ücret')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipments/', verbose_name='Görsel')),
                ('is_reservable', models.BooleanField(default=True, verbose_name='Rezerve Edilebilir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='reservations.equipmentcategory')),
            ],
            options={
                'verbose_name': 'Ekipman',
                'verbose_name_plural': 'Ekipmanlar',
            },
        ),
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi'), ('checked_out', 'Teslim Alındı'), ('returned', 'İade Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Alma Zamanı')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='İade Zamanı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.equipment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ekipman Rezervasyonu',
                'verbose_name_plural': 'Ekipman Rezervasyonları',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AreaReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi'), ('completed', 'Tamamlandı'), ('no_show', 'Gelmedi')], default='pending', max_length=20, verbose_name='Durum')),
                ('number_of_people', models.PositiveIntegerField(default=1, verbose_name='Kişi Sayısı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_reservations', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.reservablearea')),
            ],
            options={
                'verbose_name': 'Alan Rezervasyonu',
                'verbose_name_plural': 'Alan Rezervasyonları',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AreaAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Haftanın Günü')),
                ('start_time', models.TimeField(verbose_name='Açılış Saati')),
                ('end_time', models.TimeField(verbose_name='Kapanış Saati')),
                ('is_available', models.BooleanField(default=True, verbose_name='Müsait')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='reservations.reservablearea')),
            ],
            options={
                'verbose_name': 'Alan Müsaitliği',
                'verbose_name_plural': 'Alan Müsaitlikleri',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('area', 'weekday')},
            },
        ),
    ]
