# Generated by Django 5.1.7 on 2025-03-15 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paket adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Süre (gün)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Özellikler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Üyelik Planı',
                'verbose_name_plural': 'Üyelik Planları',
            },
        ),
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='Giriş zamanı')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Çıkış zamanı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giriş-Çıkış Kaydı',
                'verbose_name_plural': 'Giriş-Çıkış Kayıtları',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='MemberMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ölçüm tarihi')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kilo (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Boy (cm)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Vücut yağ oranı (%)')),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kas kütlesi (kg)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Vücut kitle indeksi (BMI)')),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Göğüs (cm)')),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bel (cm)')),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kalça (cm)')),
                ('arms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kol (cm)')),
                ('thighs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bacak (cm)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üye Ölçümü',
                'verbose_name_plural': 'Üye Ölçümleri',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş tarihi')),
                ('payment_status', models.CharField(choices=[('pending', 'Beklemede'), ('paid', 'Ödendi'), ('overdue', 'Gecikmiş'), ('cancelled', 'İptal edildi')], default='pending', max_length=20, verbose_name='Ödeme durumu')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödeme tarihi')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödenen tutar')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='members.membershipplan')),
            ],
            options={
                'verbose_name': 'Üyelik',
                'verbose_name_plural': 'Üyelikler',
            },
        ),
    ]
